FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS http://*:5000
EXPOSE 5000

# Copy csproj and restore as distinct layers
RUN pwd

# Copy everything and build
COPY . ./

RUN ls

RUN dotnet publish ./Presentation/CourseStudioManager.Api/CourseStudioManager.Api.csproj -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/Presentation/CourseStudioManager.Api/out .
ENTRYPOINT ["dotnet", "CourseStudioManager.Api.dll"]